macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

test_task:
  test_script:
    - brew install python@3.10
    - python3 -m pip install tox --upgrade
    - python3 -m tox -e py310
