[build-system]
requires = ['setuptools', 'wheel', 'cython']
build-backend = 'setuptools.build_meta'

[tool.black]
target-version = ['py38', 'py39', 'py310']
skip-string-normalization = false
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | examples
  )/
)
'''

[tool.isort]
profile = "black"
line_length = 79


[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-*"
